- name: "update packages"
  become: yes
  apt:
    name: "*"
    state: latest

- name: "Install NodeJS"
  become: yes
  apt:
    name: nodejs
    state: latest

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    state: latest
    global: yes

- name: "configure env variables"
  environment:
    ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"

- name: "start pm2"
  become: yes
  shell: sudo env PATH=$PATH:/usr/local/bin pm2 startup